name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: |
        echo "Hello World!"
        ls -las
    - name: Get code
      uses: actions/checkout@v4
      with:
        path: main
    - name: Print goodbye
      run: |
        echo "Done - bye!"
        ls -las
